version: "3"
services:
  app:
    container_name: fcm-external-docker
    restart: always
    build: .
    ports:
      - "3000:3000"
    networks:
      - fcm_service
  mongo:
    container_name: mongo_db
    image: mongo:latest
    volumes:
      - /mongodbdata:/data/db:rw
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: database
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - fcm_service

networks:
  fcm_service:
    external: true